### ISSUE TITLE
[Bug] Some people receive double rep

### ISSUE THREAD

**Issue by sttephen** [learnspigot/discord-bot#110] opened 2023-01-10 18:45 UTC
### Explain the issue.

This bug happens occassionanly, around once a day.

I don't know the cause but I will provide all information I know in the latest instance it happeend.

This showed in the ticket:
https://cdn.virtualventures.io/oqkl8

This was the output in support:
https://cdn.virtualventures.io/kxqff

**The actual outcome was Mathewoo receiving x2 rep, revel receiving x2 rep, and 5vl only receiving one rep.**

Not a clue fellas.

**Comment by Nuckerr** [comment] 2023-01-11 13:44
Very weird. Probably an issue with deployment

**Comment by Nuckerr** [comment] 2023-01-17 13:03
I believe this is a duplicate of #105. Going to close this one, #105 has more details

**Closed as completed by Nuckerr** 2023-01-17 13:03 UTC
Labels: bug, duplicate, high priority, deployment
